import Head from "next/head";
import JavascriptData from "../components/JavascriptData";

export default function Home() {

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <JavascriptData/>

      </main>

      <footer></footer>
    </div>
  );
}
